# Generated by Django 5.2.17 on 2026-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
