# Generated by Django 5.2.17 on 2026-09-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPEN_EDX', 'Open edX')], max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course_url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_external_course_provider_id')],
            },
        ),
        migrations.CreateModel(
            name='ExternalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled')], default='ENROLLED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.externalcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'external_course'), name='unique_student_external_course')],
            },
        ),
    ]
